# Generated by Django 3.0.5 on 2023-12-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolioitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='level',
            new_name='qualification',
        ),
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
        migrations.AddField(
            model_name='education',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
